In [18]:
import numpy as np#推荐引用方式
from timeit import timeit 

print(np.ones((10, 5)))
print(np.zeros((5,10)))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [20]:
print(np.ones((10, 5)).shape)
#(10, 5) 数组形状
print(np.ones((10, 5)).dtype)
#float64 数据类型
print(np.ones((10, 5)).strides)
print(np.zeros((5, 10)).strides)
#(40, 8) （80,8） 跨度元组

(10L, 5L)
float64
(40L, 8L)
(80L, 8L)


In [5]:
#测试Numpy数组和等价的Python列表性能差距
my_arr = np.arange(1000000)
my_list = list(range(1000000))
t1 = timeit('for _ in range(10): my_arr2 = my_arr * 2','from __main__ import my_arr',number=1)
t2 = timeit('for _ in range(10): my_list2 = [x * 2 for x in my_list]','from __main__ import my_list',number=1)
print(t1,t2)

(0.02188968798746771, 0.706431966066944)


In [6]:
#矢量化运算
arrA = np.array([[1., 2., 3.], [4., 5., 6.]])
arrB = np.array([[2., 2., 2.], [2., 2., 2.]])
print(arrA)

print(arrB)

print(arrA * arrB)

print(arrA * 2.0)

[[1. 2. 3.]
 [4. 5. 6.]]
[[2. 2. 2.]
 [2. 2. 2.]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]]


In [7]:
arrA = np.array([[0., 0., 0.], [1., 1., 1.], [2., 2., 2.], [3., 3., 3.]])
print(arrA)
print(arrA.shape)
#(4, 3)
arrB = np.array([1., 2., 3.])
print(arrB)
#[ 1.  2.  3.]
print(arrB.shape)
#(3,)
print(arrA+arrB)

[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]
(4L, 3L)
[1. 2. 3.]
(3L,)
[[1. 2. 3.]
 [2. 3. 4.]
 [3. 4. 5.]
 [4. 5. 6.]]


In [22]:
x = np.ones((4,1))
print(x)
y = np.ones((1,4,3))
print(y)
print(x+y)
#operands could not be broadcast together with shapes (2,1) (5,4,3)

[[1.]
 [1.]
 [1.]
 [1.]]
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [24]:
data = np.random.randn(3, 4)
print(data)

[[-0.10370398  1.09212691 -1.66726791 -0.813621  ]
 [ 0.2891542   0.98501681  0.12846652 -0.60408781]
 [ 0.95420025  1.17773203 -0.31548119 -1.16795995]]


In [10]:
print(data[[True, False, False]])
#[[ 0.81516464  0.54699707  0.25469129 -0.35725194]]
print(data[[True, False, False],1])
#[ 0.54699707]
print(data < 0)

[[ 0.81516464  0.54699707  0.25469129 -0.35725194]]
[0.54699707]
[[False False False  True]
 [ True False  True  True]
 [ True False False False]]


In [11]:
print(data[data < 0])
#[-0.35725194 -0.1594436  -0.51086806 -0.82336626 -0.76274312]

[-0.35725194 -0.1594436  -0.51086806 -0.82336626 -0.76274312]
