In [19]:
import tensorflow as tf

w1 = tf.Variable(tf.random_normal([2,3],stddev=1,mean=0,seed=2))#标准正态分布输出随机值
w2 = tf.truncated_normal([2,3])  
#tf.truncated_normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None, name=None)        
#从截断的正态分布中输出随机值。shape表示生成张量的维度，mean是均值，stddev是标准差。
w3 = tf.random_uniform([2,3])
#tf.random_uniform((6, 6), minval=low,maxval=high,dtype=tf.float32)))返回6*6的矩阵，产生于low和high之间，产生的值是均匀分布的。
w4 = tf.zeros([3,2])
w5 = tf.ones([3,2])
w6 = tf.fill([3,2],6)
w7 = tf.constant([3,2,1])

print w1,w2,w3,w4,w5,w6,w7

with tf.Session() as sess:
    init_op=tf.global_variables_initializer()
    sess.run(init_op)
    
    print sess.run(w1)
    print sess.run(w2)
    print sess.run(w3)
    print sess.run(w4)
    print sess.run(w5)
    print sess.run(w6)
    print sess.run(w7)

<tf.Variable 'Variable_17:0' shape=(2, 3) dtype=float32_ref> Tensor("truncated_normal_17:0", shape=(2, 3), dtype=float32) Tensor("random_uniform_17:0", shape=(2, 3), dtype=float32) Tensor("zeros_14:0", shape=(3, 2), dtype=float32) Tensor("ones_13:0", shape=(3, 2), dtype=float32) Tensor("Fill_12:0", shape=(3, 2), dtype=int32) Tensor("Const_12:0", shape=(3,), dtype=int32)
[[-0.85811085 -0.19662298  0.13895045]
 [-1.22127676 -0.40341285 -1.1454041 ]]
[[-0.7393536   1.42231476  0.98564249]
 [ 1.08530426 -0.08892716  0.98111445]]
[[ 0.49360466  0.25720024  0.4124434 ]
 [ 0.64933276  0.84061074  0.23855305]]
[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]
[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]
[[6 6]
 [6 6]
 [6 6]]
[3 2 1]


In [20]:
#coding:utf-8
import tensorflow as tf

#定义输入和参数
x=tf.placeholder(tf.float32,shape=(1,2))
w1=tf.Variable(tf.random_normal([2,3],stddev=1,seed=1))
w2=tf.Variable(tf.random_normal([3,1],stddev=1,seed=1))

#定义前向传播过程
a=tf.matmul(x,w1)
y=tf.matmul(a,w2)

#用会话计算结果
with tf.Session() as sess:
    init_op=tf.global_variables_initializer()
    sess.run(init_op)
    print "y in tf3_3.py is:\n",sess.run(y,feed_dict={x:[[0.7,0.5]]})

y in tf3_3.py is:
[[ 3.0904665]]


In [7]:
#coding:utf-8
import tensorflow as tf

#定义输入和参数
x=tf.placeholder(tf.float32,shape=(None,2))
w1=tf.Variable(tf.random_normal([2,3],stddev=1,seed=1))
w2=tf.Variable(tf.random_normal([3,1],stddev=1,seed=1))

#定义前向传播过程
a=tf.matmul(x,w1)
y=tf.matmul(a,w2)

#用会话计算结果
with tf.Session() as sess:
    init_op=tf.global_variables_initializer()
    sess.run(init_op)
    print "y in tf3_4.py is:\n",sess.run(y,feed_dict={x:[[0.7,0.5],[0.2,0.3],[0.3,0.4],[0.4,0.5]]})

y in tf3_4.py is:
[[ 3.0904665 ]
 [ 1.2236414 ]
 [ 1.72707319]
 [ 2.23050475]]
