In [1]:
#coding:utf-8
#预测多或预测少的影响一样
#0、导入模块，常量定义，生成模拟数据集
import tensorflow as tf
import numpy as np

BATCH_SIZE = 8
SEED = 23455

#基于seed生成随机数
rdm = np.random.RandomState(SEED)

#随机数返回32行2列的矩阵，表示32组体积和重量，作为输入数据集
X = rdm.rand(32,2)

#作为输入数据集的标签（正确答案）
Y_ = [[x1+x2+(rdm.rand()/10.0-0.05)] for (x1,x2) in X]

#1、定义神经网络的输入、参数和输出，定义前向传播过程
x = tf.placeholder(tf.float32,shape=(None,2))
y_ = tf.placeholder(tf.float32,shape=(None,1))
w1 = tf.Variable(tf.random_normal([2,1],stddev=1,seed=1))
y = tf.matmul(x,w1)

#2、定义损失函数及反向传播方法
loss_mse = tf.reduce_mean(tf.square(y_-y))
train_step = tf.train.GradientDescentOptimizer(0.001).minimize(loss_mse)
#train_step = tf.train.MomentumOptimizer(0.001).minimize(loss)
#train_step = tf.train.AdamDescentOptimizer(0.001).minimize(loss)

#3、生成会话，训练STEPS轮
with tf.Session() as sess:
    init_op = tf.global_variables_initializer()
    sess.run(init_op)
    
    print "X:\n",X
    print "Y_:\n",Y_
    
    #输出目前（未经训练）的参数取值
    print "w1:\n",sess.run(w1)
    print "\n"

    #训练模型
    STEPS = 20000
    for i in range(STEPS):
        start = (i*BATCH_SIZE) % 32
        end = start + BATCH_SIZE
        sess.run(train_step,feed_dict={x:X[start:end],y_:Y_[start:end]})
        if i % 500 == 0:
            print "After %d training steps,w1 is: " %(i)
            print sess.run(w1),"\n"

    #输出训练后的参数取值
    print "\n"
    print "Final w1 is:\n",sess.run(w1)

X:
[[0.83494319 0.11482951]
 [0.66899751 0.46594987]
 [0.60181666 0.58838408]
 [0.31836656 0.20502072]
 [0.87043944 0.02679395]
 [0.41539811 0.43938369]
 [0.68635684 0.24833404]
 [0.97315228 0.68541849]
 [0.03081617 0.89479913]
 [0.24665715 0.28584862]
 [0.31375667 0.47718349]
 [0.56689254 0.77079148]
 [0.7321604  0.35828963]
 [0.15724842 0.94294584]
 [0.34933722 0.84634483]
 [0.50304053 0.81299619]
 [0.23869886 0.9895604 ]
 [0.4636501  0.32531094]
 [0.36510487 0.97365522]
 [0.73350238 0.83833013]
 [0.61810158 0.12580353]
 [0.59274817 0.18779828]
 [0.87150299 0.34679501]
 [0.25883219 0.50002932]
 [0.75690948 0.83429824]
 [0.29316649 0.05646578]
 [0.10409134 0.88235166]
 [0.06727785 0.57784761]
 [0.38492705 0.48384792]
 [0.69234428 0.19687348]
 [0.42783492 0.73416985]
 [0.09696069 0.04883936]]
Y_:
[[0.969797861054287], [1.1634604857835003], [1.1942714411690643], [0.5384488448601839], [0.8632760602061649], [0.8339321949148727], [0.9280893354024469], [1.6879345369421652], [0.9036674505700

In [2]:
#coding:utf-8
#预测多或预测少的影响一样
#0、导入模块，常量定义，生成模拟数据集
import tensorflow as tf
import numpy as np

BATCH_SIZE = 8
SEED = 23455

#酸奶成本1元，酸奶利润9元
#预测少了损失大，故不要预测少，故生成的模型会多预测一些
COST = 1
PROFIT = 9

#基于seed生成随机数
rdm = np.random.RandomState(SEED)

#随机数返回32行2列的矩阵，表示32组体积和重量，作为输入数据集
X = rdm.rand(32,2)

#作为输入数据集的标签（正确答案）
Y_ = [[x1+x2+(rdm.rand()/10.0-0.05)] for (x1,x2) in X]

#1、定义神经网络的输入、参数和输出，定义前向传播过程
x = tf.placeholder(tf.float32,shape=(None,2))
y_ = tf.placeholder(tf.float32,shape=(None,1))
w1 = tf.Variable(tf.random_normal([2,1],stddev=1,seed=1))
y = tf.matmul(x,w1)

#2、定义损失函数及反向传播方法
#自定义损失函数使得预测少了的损失大，于是模型应该偏向多的方向预测
loss = tf.reduce_sum(tf.where(tf.greater(y,y_),(y-y_)*COST,(y_-y)*PROFIT))
train_step = tf.train.GradientDescentOptimizer(0.001).minimize(loss)

#3、生成会话，训练STEPS轮
with tf.Session() as sess:
    init_op = tf.global_variables_initializer()
    sess.run(init_op)
    #输出目前（未经训练）的参数取值
    print "w1:\n",sess.run(w1)
    print "\n"

    #训练模型
    STEPS = 20000
    for i in range(STEPS):
        start = (i*BATCH_SIZE) % 32
        end = start + BATCH_SIZE
        sess.run(train_step,feed_dict={x:X[start:end],y_:Y_[start:end]})
        if i % 500 == 0:
            print "After %d training steps,w1 is: " %(i)
            print sess.run(w1),"\n"

    #输出训练后的参数取值
    print "\n"
    print "Final w1 is:\n",sess.run(w1)

w1:
[[-0.8113182]
 [ 1.4845988]]


After 0 training steps,w1 is: 
[[-0.762993 ]
 [ 1.5095658]] 

After 500 training steps,w1 is: 
[[1.0235443]
 [1.0463386]] 

After 1000 training steps,w1 is: 
[[1.0174844]
 [1.0406483]] 

After 1500 training steps,w1 is: 
[[1.0211805]
 [1.0472497]] 

After 2000 training steps,w1 is: 
[[1.0179386]
 [1.0412899]] 

After 2500 training steps,w1 is: 
[[1.0205938]
 [1.0390677]] 

After 3000 training steps,w1 is: 
[[1.0242898]
 [1.0456691]] 

After 3500 training steps,w1 is: 
[[1.01823  ]
 [1.0399789]] 

After 4000 training steps,w1 is: 
[[1.021926 ]
 [1.0465802]] 

After 4500 training steps,w1 is: 
[[1.0245812]
 [1.044358 ]] 

After 5000 training steps,w1 is: 
[[1.0185213]
 [1.0386678]] 

After 5500 training steps,w1 is: 
[[1.0245652]
 [1.0446368]] 

After 6000 training steps,w1 is: 
[[1.0185053]
 [1.0389466]] 

After 6500 training steps,w1 is: 
[[1.0222014]
 [1.045548 ]] 

After 7000 training steps,w1 is: 
[[1.0161415]
 [1.0398577]] 

After 7500 training st