In [15]:
import math

# 假设一些随机数据和权重
w = [2,-3,-3]
x = [-1,-2]

# 前向传播 
dot = w[0]*x[0] + w[1]*x[1] + w[2] 
f = 1.0 / (1 + math.exp(-dot)) # sigmoid函数  
print(dot)
print(f)

# 对神经元反向传播 
ddot = (1 - f) * f # 点积变量的梯度, 使用sigmoid函数求导 
dx = [w[0] * ddot,w[1] * ddot] # 回传到x 
dw = [x[0] * ddot,x[1] * ddot,1.0 * ddot] # 回传到w 
print(ddot)
print(dx)
print(dw)

# 完成！得到输入的梯度

1
0.7310585786300049
0.19661193324148185
[0.3932238664829637, -0.5898357997244456]
[-0.19661193324148185, -0.3932238664829637, 0.19661193324148185]


In [30]:
import math

x = 3 # 例子数值 
y = -4   

# 前向传播 
sigy = 1.0 / (1 + math.exp(-y)) #分子中的sigmoid        #(1) 
num = x + sigy                     #分子                #(2) 
sigx = 1.0 / (1 + math.exp(-x)) #分母中的sigmoid        #(3) 
xpy = x + y                                             #(4) 
xpysqr = xpy**2                                         #(5) 
den = sigx + xpysqr #分母                               #(6) 
invden = 1.0 / den                                      #(7) 
f = num * invden #搞定!                                 #(8)

#回传 f = num * invden 
dnum = invden #分子的梯度                               #(8) 
dinvden = num  #分母倒数的梯度                              #(8) 
#回传  invden = 1.0 / den  
dden = (-1.0 / (den ** 2)) * dinvden                   #(7) 
#回传 den = sigx + xpysqr 
dsigx = (1) * dden                                     #(6) 
dxpysqr = (1) * dden                                   #(6) 
#回传 xpysqr = xpy**2 
dxpy = (2 * xpy) * dxpysqr                             #(5) 
#回传 xpy = x + y 
dx = (1) * dxpy                                       #(4) 
dy = (1) * dxpy                                       #(4) 
#回传 sigx = 1.0 / (1 + math.exp(-x)) 
dx += ((1 - sigx) * sigx) * dsigx #Notice += !! See notes below  #(3) 
#回传 num = x + sigy 
dx += (1) * dnum                                     #(2) 
dsigy = (1) * dnum                                   #(2) 
#回传 sigy = 1.0 / (1 + math.exp(-y)) 
dy += ((1 - sigy) * sigy) * dsigy                    #(1)

#对前向传播时产生每个变量(sigy, num, sigx, xpy, xpysqr, den, invden)进行回传
print(sigy,"\n",num,"\n",sigx,"\n",xpy,"\n",xpysqr,"\n",den,"\n",invden)
print("====================")
print(dsigy,"\n",dnum,"\n",dsigx,"\n",dxpy,"\n",dxpysqr,"\n",dden,"\n",dinvden)

0.01798620996209156 
 3.0179862099620918 
 0.9525741268224334 
 -1 
 1 
 1.9525741268224333 
 0.5121444488396316
0.5121444488396316 
 0.5121444488396316 
 -0.7915934472725935 
 1.583186894545187 
 -0.7915934472725935 
 -0.7915934472725935 
 3.0179862099620918


在不同分支的梯度要相加：如果变量x，y在前向传播的表达式中出现多次，那么进行反向传播的时候就要非常小 心，使用+=而不是=来累计这些变量的梯度（不然就会造成覆写）。这是遵循了在微积分中的多元链式法则，该法 则指出如果变量在线路中分支走向不同的部分，那么梯度在回传的时候，就应该进行累加。 

In [63]:
import numpy as np

#前向传播
W = np.random.randn(5, 10)    # (1)
X = np.random.randn(10, 3)    # (2)
D = W.dot(X)                  # (3)

# 假设我们得到了D的梯度 
# 回传 D = W.dot(X)
dD = np.random.randn(*D.shape) # 和D一样的尺寸  #(3)
# 回传 W = np.random.randn(5, 10)
dW = dD.dot(X.T) #.T就是对矩阵进行转置         # (1)
# 回传 X = np.random.randn(10, 3)
dX = (W.T).dot(dD)                             # (2)

print(W,"\n",X,"\n",D)
print("\n")
print(dW,"\n",dX,"\n",dD)

[[ 0.38272086 -0.52998293  1.01144379 -0.81495806  2.54328878 -0.02388854
  -0.43918269 -0.8249908  -1.58517481  0.76942859]
 [-0.32017829 -1.24027204 -1.06858249  0.06713299 -1.11500651  0.94863734
  -0.24139851 -1.70992383  0.09674566 -0.68595949]
 [ 0.86457456  0.97510965 -0.42698194 -0.69782274 -1.29249798 -0.85676004
   0.80393451 -1.22423633 -0.5255172   0.51931101]
 [ 0.36719722  0.98366924 -2.68496987 -0.56667781 -1.74714164 -1.69399606
   0.16343184 -0.31638368  1.47811653  1.09880961]
 [-0.23316953 -0.06621757  0.62349162 -1.19615896  0.31397935 -0.27228482
   0.49449042 -1.00496085 -0.12532659  0.2738066 ]] 
 [[-0.52266475 -1.0499927   1.19618699]
 [-0.21766677 -0.19495962  1.33616153]
 [ 0.08179345  0.69996756 -0.74807993]
 [-0.30013887  0.25130981 -1.2056558 ]
 [-0.4126432  -0.38798206 -1.59637848]
 [ 0.54886456  0.53602732 -2.39561577]
 [ 0.44123218 -1.09714189 -0.1234121 ]
 [-1.94640212  1.08016075 -0.22489038]
 [ 0.24023661 -0.73116088  0.16031246]
 [-0.96326297 -0.5560