In [9]:
# -*- conding：utf-8 -*-

import numpy as np
from numpy.linalg import inv#矩阵的逆
from numpy import dot#点乘
from numpy import mat#矩阵

A = np.mat([1,1])
print('A:\n',A)
print('A.T:\n',A.T)
print('A.reshape:\n',A.reshape(2,1))#重新构造矩阵
print('-------------')

B = mat([[1,2],[2,3]])
print('B：\n',B)
print('B.reshape：\n',B.reshape(1,4))
print('-------------')
print('B的逆:\n',inv(B))
print('B的第一行：\n',B[0,:])
print('B的第一列：”\n',B[:,0])

#A 1*2 B 2*2
print('A.B:\n',dot(B,A.T))

A:
 [[1 1]]
A.T:
 [[1]
 [1]]
A.reshape:
 [[1]
 [1]]
-------------
B：
 [[1 2]
 [2 3]]
B.reshape：
 [[1 2 2 3]]
-------------
B的逆:
 [[-3.  2.]
 [ 2. -1.]]
B的第一行：
 [[1 2]]
B的第一列：”
 [[1]
 [2]]
A.B:
 [[3]
 [5]]


#### 通过正规方程求theta

In [10]:
# -*- conding：utf-8 -*-

import numpy as np
from numpy.linalg import inv#矩阵的逆
from numpy import dot#点乘
from numpy import mat#矩阵

#y=2x
X = mat([1,2,3]).reshape(3,1)
print('X:\n',X)
Y = 2 * X
print('Y:\n',Y)

#theta = (X'X)^X'Y  '表示转置、^表示逆
theta = dot(dot(inv(dot(X.T,X)),X.T),Y)
print(theta)

X:
 [[1]
 [2]
 [3]]
Y:
 [[2]
 [4]
 [6]]
[[ 2.]]


In [12]:
# -*- conding：utf-8 -*-

import numpy as np
from numpy.linalg import inv#矩阵的逆
from numpy import dot#点乘
from numpy import mat#矩阵

#y=2x
X = mat([1,2,3]).reshape(3,1)
Y = 2 * X

#theta = (X'X)^X'Y

#theta = dot(dot(inv(dot(X.T,X)),X.T),Y)

#theta = theta - alpha * (theta * X - Y) * X

theta = 1.

alpha = 0.1

for i in range(100):
    theta = theta + np.sum(alpha * (Y - dot(X,theta)) * X.reshape(1,3)) / 3.
    #theta = theta - np.sum(alpha * (dot(X,theta) - Y) * X.reshape(1,3)) / 3.

print(theta)

2.0


In [20]:
# -*- conding：utf-8 -*-

import numpy as np
from numpy.linalg import inv#矩阵的逆
from numpy import dot#点乘
from numpy import mat#矩阵
import pandas as pd

dataset = pd.read_csv('./data.csv')
#print(dataset)
# 0 Y X1 X2 X3
# 1 5.1 3.5 1.4 0.2
temp = dataset.iloc[:,2:5]
temp['x0'] = 1
X = temp.iloc[:,[3,0,1,2]]
#print(X)
Y = dataset.iloc[:,1].values.reshape(150,1)
#print(Y)
theta = dot(dot(inv(dot(X.T,X)),X.T),Y)
print(theta.reshape(4,1))

theta = np.array([1.,1.,1.,1.]).reshape(4,1)
alpha = 0.1
X0 = X.iloc[:,0].reshape(150,1)
X1 = X.iloc[:,1].reshape(150,1)
X2 = X.iloc[:,2].reshape(150,1)
X3 = X.iloc[:,3].reshape(150,1)

for i in range(10000):
    temp[0] = theta[0] + alpha * np.sum((Y - dot(X,theta)) * X0) / 150.
    temp[1] = theta[1] + alpha * np.sum((Y - dot(X,theta)) * X1) / 150.
    temp[2] = theta[2] + alpha * np.sum((Y - dot(X,theta)) * X2) / 150.
    temp[3] = theta[3] + alpha * np.sum((Y - dot(X,theta)) * X3) / 150.
    theta = temp
print(theta)

[[ 5.08114946]
 [-0.11129722]
 [ 0.01257887]
 [ 0.28824829]]


ValueError: Length of values does not match length of index