In [1]:
import tensorflow as tf

a = tf.constant([1.0,2.0],name="a")
b = tf.constant([2.0,3.0],name="b")

result = a + b

print(result)

print(a.graph is tf.get_default_graph())

Tensor("add:0", shape=(2,), dtype=float32)
True


In [2]:
import tensorflow as tf

g1 = tf.Graph()
with g1.as_default():
    v = tf.get_variable(
    "v",initializer=tf.zeros_initializer(shape = [1]))
    
g2 = tf.Graph()
with g2.as_default():
    v = tf.get_variable(
    "v",initializer=tf.ones_initializer(shape = [1]))
    
with tf.Session(graph=g1) as sess:
    tf.initailize_all_variables().run()
    with tf.variable_scope("",reuse=True):
        print(sess.run(tf.get_variable("v")))
    
with tf.Session(graph=g2) as sess:
    tf.initailize_all_variables().run()
    with tf.variable_scope("",reuse=True):
        print(sess.run(tf.get_variable("v")))
        
g = tf.Graph()
with g.device('/gpu:0'):
    result = a + b

TypeError: __init__() got an unexpected keyword argument 'shape'

In [3]:
import tensorflow as tf

a = tf.constant([1.0,2.0],name="a")
b = tf.constant([2.0,3.0],name="b")

result = tf.add(a,b,name="add")

print(result)

Tensor("add_1:0", shape=(2,), dtype=float32)


In [4]:
import tensorflow as tf

a = tf.constant([1,2],name="a")
b = tf.constant([2.0,3.0],name="b")

result = a + b

result = tf.constant([1,2],name="a") + tf.constant([2.0,3.0],name="b")

TypeError: Input 'y' of 'Add' Op has type float32 that does not match type int32 of argument 'x'.

In [5]:
sess = tf.Session()

sess.run()

sess.close()

TypeError: run() missing 1 required positional argument: 'fetches'

In [6]:
with tf.Session() as sess:
    sess.run()

TypeError: run() missing 1 required positional argument: 'fetches'

In [7]:
sess = tf.Session()
with sess.as_default():
    print(result.eval())

[3. 5.]


In [8]:
sess = tf.Session()
print(sess.run(result))
print(result.eval(session=sess))

[3. 5.]
[3. 5.]


In [9]:
sess = tf.InteractiveSession()
print(result.eval())
sess.close()

[3. 5.]


In [10]:
config = tf.ConfigProto(allow_aoft_placement=True,log_device_placement=True)
sess1 = tf.InteractiveSession(config=config)
sess2 = tf.Session(config=config)

ValueError: Protocol message ConfigProto has no "allow_aoft_placement" field.

In [12]:
a = tf.matmul(x,w1)
y = tf.matmul(a,w2)

weights = tf.Variable(tf.random_normal([2,3],stddev=2))

biases = tf.Variable(tf.zeros([3]))

w2 = tf.Variable(weights.initialized_value())
w3 = tf.Variable(weights.initialized_value() * 2.0)

NameError: name 'x' is not defined

In [15]:
import tensorflow as tf

w1 = tf.Variable(tf.random_normal([2,3],stddev=1,seed=1))
w2 = tf.Variable(tf.random_normal([3,1],stddev=1,seed=1))
print(w1)
print(w2)

x = tf.constant([[0.7,0.9]])
print(x)

#输入层x，隐藏层a，输出层y
#矩阵乘法很容易实现
a = tf.matmul(x,w1)
y = tf.matmul(a,w2)
print(a)
print(y)

sess = tf.Session()

sess.run(w1.initializer)
sess.run(w2.initializer)

print(sess.run(y))
sess.close()

<tf.Variable 'Variable_4:0' shape=(2, 3) dtype=float32_ref>
<tf.Variable 'Variable_5:0' shape=(3, 1) dtype=float32_ref>
Tensor("Const_2:0", shape=(1, 2), dtype=float32)
Tensor("MatMul_4:0", shape=(1, 3), dtype=float32)
Tensor("MatMul_5:0", shape=(1, 1), dtype=float32)
[[3.957578]]


In [ ]:
init_op = tf.initialize_all_variables()
sess.run(init_op)

In [16]:
w1 = tf.Variable(tf.random_normal([2,3],stddev=1),name="w1")
w2 = tf.Variable(tf.random_normal([2,2],stddev=1),name="w2")

#将w2的值赋值给w1
w1.assign(w2) #报错

tf.assign(w1,w2) #报错

tf.assign(w1,w2,validate_shape=False)

ValueError: Dimension 1 in both shapes must be equal, but are 3 and 2. Shapes are [2,3] and [2,2]. for 'Assign' (op: 'Assign') with input shapes: [2,3], [2,2].

In [18]:
import tensorflow as tf

w1 = tf.Variable(tf.random_normal([2,3],stddev=1,seed=1))
w2 = tf.Variable(tf.random_normal([3,1],stddev=1,seed=1))
print(w1)
print(w2)

x = tf.placeholder(tf.float32,shape=(1,2),name="input")
print(x)

#输入层x，隐藏层a，输出层y
#矩阵乘法很容易实现
a = tf.matmul(x,w1)
y = tf.matmul(a,w2)
print(a)
print(y)

sess = tf.Session()
init_op = tf.initialize_all_variables()
sess.run(init_op)

#print(sess.run(y))

print(sess.run(y,feed_dict={x:[[0.7,0.9]]}))

print(sess.run(y,feed_dict={x:[[0.7,0.9],[0.1,0.4],[0.5,0.8]]}))

sess.close()

<tf.Variable 'Variable_8:0' shape=(2, 3) dtype=float32_ref>
<tf.Variable 'Variable_9:0' shape=(3, 1) dtype=float32_ref>
Tensor("input_1:0", shape=(1, 2), dtype=float32)
Tensor("MatMul_8:0", shape=(1, 3), dtype=float32)
Tensor("MatMul_9:0", shape=(1, 1), dtype=float32)
[[3.957578]]


In [19]:
import tensorflow as tf

w1 = tf.Variable(tf.random_normal([2,3],stddev=1,seed=1))
w2 = tf.Variable(tf.random_normal([3,1],stddev=1,seed=1))
print(w1)
print(w2)

x = tf.placeholder(tf.float32,shape=(3,2),name="input")
print(x)

#输入层x，隐藏层a，输出层y
#矩阵乘法很容易实现
a = tf.matmul(x,w1)
y = tf.matmul(a,w2)
print(a)
print(y)

sess = tf.Session()
init_op = tf.initialize_all_variables()
sess.run(init_op)

#print(sess.run(y))

print(sess.run(y,feed_dict={x:[[0.7,0.9],[0.1,0.4],[0.5,0.8]]}))

sess.close()

<tf.Variable 'Variable_10:0' shape=(2, 3) dtype=float32_ref>
<tf.Variable 'Variable_11:0' shape=(3, 1) dtype=float32_ref>
Tensor("input_2:0", shape=(3, 2), dtype=float32)
Tensor("MatMul_10:0", shape=(3, 3), dtype=float32)
Tensor("MatMul_11:0", shape=(3, 1), dtype=float32)
[[3.957578 ]
 [1.1537654]
 [3.1674924]]


In [ ]:
#损失函数
#tf.reduce_mean 函数用于计算张量tensor沿着指定的数轴（tensor的某一维度）上的的平均值，主要用作降维或者计算tensor（图像）的平均值
#tf.log：计算TensorFlow的自然对数
#tf.clip_by_value(t, clip_value_min, clip_value_max, name=None)，功能：基于定义的min与max对tesor数据进行截断操作，目的是为了应对梯度爆发或者梯度消失的情况
cross_entropy = -tf.reduce_mean(y_ * tf.log(tf.clip_by_value(y,1e-10,1.0)))
#学习率
learning_rate = 0.01
#反向传播算法调参
#tf.train.AdamOptimizer  __init__(learning_rate=0.001, beta1=0.9, beta2=0.999, epsilon=1e-08, use_locking=False, name='Adam')
#此函数是Adam优化算法：是一个寻找全局最优点的优化算法，引入了二次方梯度校正；相比于基础SGD算法，1.不容易陷于局部优点，2.速度更快
train_step = tf.train.AdamOptimizer(learning_rate).minimize(cross_entropy)

In [1]:
# 训练神经网络解决二分类问题
import tensorflow as tf

from numpy.random import RandomState

batch_size = 8

# tf.random_normal()函数用于从服从指定正太分布的数值中取出指定个数的值。
# tf.random_normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None, name=None)
#     shape: 输出张量的形状，必选
#     mean: 正态分布的均值，默认为0
#     stddev: 正态分布的标准差，默认为1.0
#     dtype: 输出的类型，默认为tf.float32
#     seed: 随机数种子，是一个整数，当设置之后，每次生成的随机数都一样
#     name: 操作的名称
w1 = tf.Variable(tf.random_normal([2,3],stddev=1,seed=1))
w2 = tf.Variable(tf.random_normal([3,1],stddev=1,seed=1))

x = tf.placeholder(tf.float32,shape=(None,2),name="x-input")
y_ = tf.placeholder(tf.float32,shape=(None,1),name="y-input")

a = tf.matmul(x,w1)
y = tf.matmul(a,w2)

cross_entropy = -tf.reduce_mean(y_ * tf.log(tf.clip_by_value(y,1e-10,1.0)))
learning_rate = 0.01
train_step = tf.train.AdamOptimizer(learning_rate).minimize(cross_entropy)

rdm = RandomState(1)
dataset_size = 128
X = rdm.rand(dataset_size,2)
Y = [[int(x1+x2 < 1)] for (x1,x2) in X]

with tf.Session() as sess:
    init_op = tf.initialize_all_variables()
    sess.run(init_op)
    print(sess.run(w1))
    print(sess.run(w2))
    
    STEPS = 5000
    for i in range(STEPS):
        start = (i * batch_size) % dataset_size
        end = min(start+batch_size,dataset_size)
        sess.run(train_step,feed_dict={x:X[start:end],y_:Y[start:end]})
        if i % 1000 == 0:
            total_cross_entropy = sess.run(cross_entropy,feed_dict={x:X[start:end],y_:Y[start:end]})
            print("After %d training steps,cross entropy on all data is %g" %(i,total_cross_entropy))
            
    print(sess.run(w1))
    print(sess.run(w2))

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Use `tf.global_variables_initializer` instead.
[[-0.8113182   1.4845988   0.06532937]
 [-2.4427042   0.0992484   0.5912243 ]]
[[-0.8113182 ]
 [ 1.4845988 ]
 [ 0.06532937]]
After 0 training steps,cross entropy on all data is 0.106783
After 1000 training steps,cross entropy on all data is -0
After 2000 training steps,cross entropy on all data is -0
After 3000 training steps,cross entropy on all data is -0
After 4000 training steps,cross entropy on all data is -0
[[-2.4540348  3.022714   2.922476 ]
 [-3.9022913  1.4489784  3.4259934]]
[[-2.1807733]
 [ 3.2438502]
 [ 2.4208493]]
